-- CREATE USER ho9njjeiqk WITH PASSWORD '0KMAxAqxY1k6LSPTAPdF' CREATEDB;
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA psfofjirb5 TO Ho9njjEiqK;

CREATE TABLE Permission(
id serial PRIMARY KEY,
name VARCHAR(50) UNIQUE NOT NULL,
description VARCHAR(255)
);
CREATE TABLE Employee(
id serial PRIMARY KEY,
name VARCHAR(255) NOT NULL,
cpf VARCHAR(11) UNIQUE NOT NULL,
username VARCHAR(50) UNIQUE NOT NULL,
password VARCHAR(50) NOT NULL,
create_on TIMESTAMP WITH TIME ZONE NOT NULL,
active BOOL NOT NULL,
type INT REFERENCES Permission (id) NOT NULL
);
CREATE TABLE Attendance(
id serial PRIMARY KEY,
user_id INT REFERENCES Employee (id) NOT NULL,
date TIMESTAMP WITH TIME ZONE NOT NULL
);

